language: vala
sudo: required
dist: trusty
compiler:
 - gcc
 - clang
cache: ccache
env:
  - DISPLAY=:99.0

install:
# Utils
 - sudo apt-add-repository ppa:vala-team/ppa -y
 - sudo apt-add-repository ppa:mc3man/trusty-media -y

# Travis requires gtk+ 3.16 to compile.
 - sudo add-apt-repository ppa:rebuntu16/glade-3.19+-trusty -y

 - sudo apt-get update -q
 - sudo apt-get install -y checkinstall build-essential texinfo libgtk-3-dev libglib2.0-dev libgdk-pixbuf2.0-dev libsoup2.4-dev libjson-glib-dev libnotify-bin python3 python valac-0.30 libnotify-dev libopus-dev ffmpeg
 - sudo apt-get install -y gtk+3.0
 - sudo apt-get install -y lcov

before_script:
# ninja
 - git clone git://github.com/martine/ninja.git
 - cd ninja
 - git checkout release
 - ./configure.py --bootstrap
 - sudo cp ./ninja /usr/bin/ninja
 - cd ..
# Gcovr
 - wget https://github.com/eraserix/gcovr/archive/3.1.tar.gz
 - tar -xvf 3.1.tar.gz
 - cd gcovr-3.1
 - sudo python setup.py install
 - cd ..
# meson
 - git clone https://github.com/mesonbuild/meson.git
 - cd meson
 - sudo python3 setup.py install
 - cd ..
# filter_audio
 - git clone https://github.com/irungentoo/filter_audio
 - cd filter_audio
 - make -j$(nproc)
 - sudo make install
 - cd ..
# libsodium
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - git checkout tags/1.0.3
 - ./autogen.sh
 - ./configure && make -j$(nproc)
 - sudo checkinstall --install --pkgname libsodium --pkgversion 1.0.0 --nodoc -y
 - sudo ldconfig
 - cd ..
# Toxcore
 - git clone https://github.com/irungentoo/toxcore.git
 - cd toxcore
 - autoreconf -if
 - ./configure
 - make -j$(nproc)
 - sudo make install
 - echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
 - sudo ldconfig
 - cd ..

script:
# Test if commit message is valid, else fail.
 - |
 if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]];
  then bash ./tools/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE";
 fi
 - rm -rf build
 - mkdir -p build
 - /usr/local/bin/meson.py . build -Db_coverage=true
 - sudo make install

notifications:
 email: false
 irc:
  channels:
   - "chat.freenode.net#ricin-dev"
  on_success: change
  on_failure: always

after_success:
# X Virtual Framebuffer
 - sh -e /etc/init.d/xvfb start; sleep 3
# Coverage
 - sudo ninja -C build
 - sudo ninja -C build test
 - cd build && ./Ricin & sleep 30s; kill %1; cd ..
 - sudo ninja -C build coverage-html
 - bash <(curl -s https://codecov.io/bash)
